title: CyberLearn
description: Lộ trình học an toàn thông tin thực chiến bằng tiếng Việt
url: https://aerovfx.github.io
baseurl: /cybersercurity
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
encoding: utf-8
exclude:
  - .git
  - .github

